<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.quarkiverse.flags</groupId>
        <artifactId>quarkus-flags-hibernate-reactive-parent</artifactId>
        <version>1.0.1</version>
    </parent>
    <artifactId>quarkus-flags-hibernate-reactive-deployment</artifactId>
    <name>Quarkus Feature Flags - Hibernate Reactive - Deployment</name>
    <dependencies>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-hibernate-reactive-deployment</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkiverse.flags</groupId>
            <artifactId>quarkus-flags-hibernate-common-deployment</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>io.quarkiverse.flags</groupId>
            <artifactId>quarkus-flags-hibernate-reactive</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-junit-internal</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-hibernate-reactive-panache-deployment</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-reactive-pg-client</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>io.quarkus</groupId>
                            <artifactId>quarkus-extension-processor</artifactId>
                            <version>${quarkus.version}</version>
                        </path>
                    </annotationProcessorPaths>
                </configuration>
            </plugin>
        </plugins>
    </build>
    <profiles>
        <profile>
            <id>test-coverage</id>
            <activation>
                <property>
                    <name>jacoco</name>
                </property>
            </activation>
            <dependencies>
                <dependency>
                    <groupId>io.quarkus</groupId>
                    <artifactId>quarkus-jacoco</artifactId>
                    <scope>test</scope>
                </dependency>
            </dependencies>
            <build>
                <plugins>
                    <plugin>
                        <artifactId>maven-surefire-plugin</artifactId>
                        <configuration>
                            <systemPropertyVariables>
                                <quarkus.jacoco.instrument-artifacts.api.group-id>io.quarkiverse.flags</quarkus.jacoco.instrument-artifacts.api.group-id>
                                <quarkus.jacoco.instrument-artifacts.api.artifact-id>quarkus-flags-api</quarkus.jacoco.instrument-artifacts.api.artifact-id>
                                <quarkus.jacoco.instrument-artifacts.core.group-id>io.quarkiverse.flags</quarkus.jacoco.instrument-artifacts.core.group-id>
                                <quarkus.jacoco.instrument-artifacts.core.artifact-id>quarkus-flags</quarkus.jacoco.instrument-artifacts.core.artifact-id>
                                <quarkus.jacoco.instrument-artifacts.hc.group-id>io.quarkiverse.flags</quarkus.jacoco.instrument-artifacts.hc.group-id>
                                <quarkus.jacoco.instrument-artifacts.hc.artifact-id>quarkus-flags-hibernate-common</quarkus.jacoco.instrument-artifacts.hc.artifact-id>
                                <quarkus.jacoco.instrument-artifacts.hr.group-id>io.quarkiverse.flags</quarkus.jacoco.instrument-artifacts.hr.group-id>
                                <quarkus.jacoco.instrument-artifacts.hr.artifact-id>quarkus-flags-hibernate-reactive</quarkus.jacoco.instrument-artifacts.hr.artifact-id>
                            </systemPropertyVariables>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>

  <scm>
    <tag>1.0.1</tag>
  </scm>
</project>
